const ZONES=[{key:"noGo",label:"Into wind / No-go",angle:"0–30°",min:0,max:30,target:0,color:"#D9383A",trim:"No useful drive",memory:"Wind on your nose. This is not a normal sailing angle.",futureTrim:"Do not fix this by pulling harder. Bear away until the bow leaves the red sector.",main:4,genoa:4},{key:"closeHauled",label:"Close-hauled",angle:"30–45°",min:30,max:45,target:38,color:"#FF8A35",trim:"Sails tight",memory:"Wind forward on your cheek. You are climbing upwind, not aiming straight into it.",futureTrim:"Sails as tight as possible. Genoa stays within the bounds of the boat.",main:12,genoa:10},{key:"closeReach",label:"Close reach",angle:"45–70°",min:45,max:70,target:58,color:"#F2C94C",trim:"Main centred, genoa by telltales",memory:"Wind still forward, but less aggressive. Think forward shoulder rather than nose.",futureTrim:"Main stays in the middle. Genoa is trimmed by telltales.",main:20,genoa:24},{key:"beamReach",label:"Beam reach",angle:"70–110°",min:70,max:110,target:90,color:"#2EB872",trim:"Boom tip at hull side",memory:"Wind on your ear or shoulder. A clear, balanced point of sail.",futureTrim:"Boom tip on the side of the hull. Genoa trim by telltales.",main:45,genoa:43},{key:"broadReach",label:"Broad reach",angle:"110–150°",min:110,max:150,target:130,color:"#2F80ED",trim:"Well eased",memory:"Wind from behind your ear. Comfortable, but the boom becomes more important.",futureTrim:"Ease mainsail until the spreader creates a horizontal crease. Genoa loose, but not overtaking the imaginary line in front of the boat.",main:68,genoa:62},{key:"deadRun",label:"Dead run",angle:"150–180°",min:150,max:180,target:180,color:"#8E44AD",trim:"Wings / butterfly",memory:"Wind behind your head. Quiet feeling, but accidental gybe risk increases.",futureTrim:"Both sails trimmed as broad reach but on both sides of the mast: Butterfly / Milkmaid / Wings.",main:86,genoa:-74}];
const CENTER={x:500,y:420};const RADIUS=260;let heading=38;let side=1;let dragging=false;const els={};
document.addEventListener("DOMContentLoaded",()=>{cache();drawTicks();drawSectors();bind();update(38);});
function cache(){els.diagram=document.querySelector("#diagram");els.simulator=document.querySelector("#simulator");els.sectorLayer=document.querySelector("#sectorLayer");els.boatGroup=document.querySelector("#boatGroup");els.mainSail=document.querySelector("#mainSail");els.genoaSail=document.querySelector("#genoaSail");els.svgPointName=document.querySelector("#svgPointName");els.factPoint=document.querySelector("#factPoint");els.factAngle=document.querySelector("#factAngle");els.factTack=document.querySelector("#factTack");els.memoryText=document.querySelector("#memoryText");els.trimText=document.querySelector("#trimText");els.buttons=[...document.querySelectorAll(".point-button[data-target]")];els.toast=document.querySelector("#toast");els.hamburgerButton=document.querySelector("#hamburgerButton");els.mobileMenu=document.querySelector("#mobileMenu");els.feedbacks=[document.querySelector("#feedbackButton"),document.querySelector("#railFeedback"),document.querySelector("#mobileFeedback"),document.querySelector("#menuFeedback")].filter(Boolean);}
function bind(){els.buttons.forEach(button=>{button.addEventListener("click",()=>{const target=Number(button.dataset.target);update(target*side);});});els.simulator.addEventListener("pointerdown",event=>{dragging=true;els.simulator.setPointerCapture?.(event.pointerId);updateFromPointer(event);});els.simulator.addEventListener("pointermove",event=>{if(!dragging)return;updateFromPointer(event);});els.simulator.addEventListener("pointerup",()=>dragging=false);els.simulator.addEventListener("pointercancel",()=>dragging=false);els.hamburgerButton?.addEventListener("click",()=>{els.mobileMenu.hidden=!els.mobileMenu.hidden;});els.feedbacks.forEach(button=>{button.addEventListener("click",()=>{showToast("Feedback form comes later. For this sprint, screenshot problems and describe what feels wrong.");if(els.mobileMenu)els.mobileMenu.hidden=true;});});}
function updateFromPointer(event){const point=svgPoint(event.clientX,event.clientY);const dx=point.x-CENTER.x;const dy=point.y-CENTER.y;let raw=Math.atan2(dx,-dy)*180/Math.PI;raw=((raw%360)+360)%360;if(raw>180)raw=raw-360;update(raw);}
function update(value){heading=clamp(value,-180,180);if(Math.abs(heading)>2)side=heading<0?-1:1;const relative=Math.abs(heading);const zone=getZone(relative);els.boatGroup.setAttribute("transform",`translate(500 420) rotate(${heading})`);drawActiveSectors(zone,heading);updateSails(zone,heading);els.svgPointName.textContent=zone.label;els.factPoint.textContent=zone.label;els.factAngle.textContent=zone.angle;els.factTack.textContent=relative<30?"No tack / into wind":side>0?"Starboard tack":"Port tack";els.memoryText.textContent=zone.memory;els.trimText.textContent=zone.futureTrim;els.buttons.forEach(button=>{const buttonZone=getZone(Number(button.dataset.target));button.classList.toggle("active",buttonZone.key===zone.key);button.style.background=buttonZone.key===zone.key?zone.color:"";});}
function updateSails(zone,headingValue){const sailSide=headingValue>=0?-1:1;let mainSide=sailSide,genoaSide=sailSide;if(zone.key==="deadRun"){mainSide=sailSide;genoaSide=-sailSide;}const mainAngle=mainSide*zone.main;const genoaAngle=genoaSide*zone.genoa;els.mainSail.setAttribute("d",mainPath(mainAngle));els.genoaSail.setAttribute("d",genoaPath(genoaAngle));}
function mainPath(angle){const head={x:0,y:-55};const tack={x:0,y:18};const clew=rotatePoint(0,18,0,-132,angle);return`M ${head.x} ${head.y} L ${tack.x} ${tack.y} L ${clew.x.toFixed(1)} ${clew.y.toFixed(1)} Z`;}
function genoaPath(angle){const head={x:0,y:-150};const tack={x:0,y:-55};const clew=rotatePoint(0,-55,0,-166,angle);return`M ${head.x} ${head.y} L ${tack.x} ${tack.y} L ${clew.x.toFixed(1)} ${clew.y.toFixed(1)} Z`;}
function rotatePoint(cx,cy,x,y,angle){const a=angle*Math.PI/180;const dx=x-cx,dy=y-cy;return{x:cx+dx*Math.cos(a)-dy*Math.sin(a),y:cy+dx*Math.sin(a)+dy*Math.cos(a)};}
function getZone(angle){return ZONES.find(zone=>angle>=zone.min&&angle<=zone.max)||ZONES[ZONES.length-1];}
function drawSectors(){drawActiveSectors(ZONES[1],38);}
function drawActiveSectors(active,headingValue){els.sectorLayer.innerHTML="";const relMin=active.min,relMax=active.max;let start,end;if(active.key==="noGo"){start=-30;end=30;}else{const s=headingValue<0?-1:1;start=s>0?relMin:-relMax;end=s>0?relMax:-relMin;}const path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("class",`sector active ${active.key==="noGo"?"no-go":""}`);path.setAttribute("fill",active.color);path.setAttribute("d",sectorPath(start,end,RADIUS+46));els.sectorLayer.appendChild(path);}
function sectorPath(start,end,radius){const p1=polar(start,radius);const p2=polar(end,radius);const sweep=end>start?1:0;return`M 0 0 L ${p1.x} ${p1.y} A ${radius} ${radius} 0 0 ${sweep} ${p2.x} ${p2.y} Z`;}
function polar(angleDeg,radius){const rad=angleDeg*Math.PI/180;return{x:(Math.sin(rad)*radius).toFixed(2),y:(-Math.cos(rad)*radius).toFixed(2)};}
function drawTicks(){const ticks=document.querySelector("#ticks");for(let angle=-180;angle<=180;angle+=10){const major=angle%30===0;const inner=major?226:240;const outer=258;const p1=polar(angle,inner);const p2=polar(angle,outer);const line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttribute("x1",p1.x);line.setAttribute("y1",p1.y);line.setAttribute("x2",p2.x);line.setAttribute("y2",p2.y);line.setAttribute("stroke","rgba(10,37,64,.36)");line.setAttribute("stroke-width",major?"4":"2");line.setAttribute("stroke-linecap","round");ticks.appendChild(line);}}
function svgPoint(clientX,clientY){const pt=els.diagram.createSVGPoint();pt.x=clientX;pt.y=clientY;return pt.matrixTransform(els.diagram.getScreenCTM().inverse());}
function showToast(message){els.toast.textContent=message;els.toast.classList.add("visible");window.clearTimeout(showToast.timer);showToast.timer=window.setTimeout(()=>els.toast.classList.remove("visible"),3500);}
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
