const ZONES=[{key:"noGo",label:"Into wind / No-go",angle:"0–30°",min:0,max:30,target:0,color:"#D9383A",memory:"Wind on your nose. This is not a normal sailing angle.",trim:"Do not fix this by pulling harder. Bear away until the bow leaves the red sector."},{key:"closeHauled",label:"Close-hauled",angle:"30–45°",min:30,max:45,target:38,color:"#FF8A35",memory:"Wind forward on your cheek. You are climbing upwind, not aiming straight into it.",trim:"Sails as tight as possible. Genoa stays within the bounds of the boat."},{key:"closeReach",label:"Close reach",angle:"45–70°",min:45,max:70,target:58,color:"#F2C94C",memory:"Wind still forward, but less aggressive. Think forward shoulder rather than nose.",trim:"Main stays in the middle. Genoa is trimmed by telltales."},{key:"beamReach",label:"Beam reach",angle:"70–110°",min:70,max:110,target:90,color:"#2EB872",memory:"Wind on your ear or shoulder. A clear, balanced point of sail.",trim:"Boom tip on the side of the hull. Genoa trim by telltales."},{key:"broadReach",label:"Broad reach",angle:"110–150°",min:110,max:150,target:130,color:"#2F80ED",memory:"Wind from behind your ear. Comfortable, but the boom becomes more important.",trim:"Ease mainsail until the spreader creates a horizontal crease. Genoa loose, but not overtaking the imaginary line in front of the boat."},{key:"deadRun",label:"Dead run",angle:"150–180°",min:150,max:180,target:180,color:"#8E44AD",memory:"Wind behind your head. Quiet feeling, but accidental gybe risk increases.",trim:"Both sails trimmed as broad reach but on both sides of the mast: Butterfly / Milkmaid / Wings."}];
const CENTER={x:500,y:420},RADIUS=260;let heading=38,lastSide=1,dragging=false;const els={};
document.addEventListener("DOMContentLoaded",()=>{cache();drawTicks();drawSectors();bind();update(38);});
function cache(){els.diagram=document.querySelector("#diagram");els.simulator=document.querySelector("#simulator");els.sectorLayer=document.querySelector("#sectorLayer");els.boatGroup=document.querySelector("#boatGroup");els.genoaSail=document.querySelector("#genoaSail");els.mainSail=document.querySelector("#mainSail");els.boomLine=document.querySelector("#boomLine");els.svgPointName=document.querySelector("#svgPointName");els.factPoint=document.querySelector("#factPoint");els.factAngle=document.querySelector("#factAngle");els.factTack=document.querySelector("#factTack");els.memoryText=document.querySelector("#memoryText");els.trimText=document.querySelector("#trimText");els.buttons=[...document.querySelectorAll(".point-button[data-target]")];els.toast=document.querySelector("#toast");els.hamburgerButton=document.querySelector("#hamburgerButton");els.mobileMenu=document.querySelector("#mobileMenu");els.feedbacks=[document.querySelector("#feedbackButton"),document.querySelector("#railFeedback"),document.querySelector("#mobileFeedback"),document.querySelector("#menuFeedback")].filter(Boolean)}
function bind(){els.buttons.forEach(b=>b.addEventListener("click",()=>update(Number(b.dataset.target))));els.simulator.addEventListener("pointerdown",e=>{dragging=true;els.simulator.setPointerCapture?.(e.pointerId);updateFromPointer(e)});els.simulator.addEventListener("pointermove",e=>{if(dragging)updateFromPointer(e)});els.simulator.addEventListener("pointerup",()=>dragging=false);els.simulator.addEventListener("pointercancel",()=>dragging=false);els.hamburgerButton?.addEventListener("click",()=>els.mobileMenu.hidden=!els.mobileMenu.hidden);els.feedbacks.forEach(b=>b.addEventListener("click",()=>{showToast("Feedback form comes after the boat model is accepted. Screenshot the issue and describe what feels wrong.");if(els.mobileMenu)els.mobileMenu.hidden=true}))}
function updateFromPointer(e){const p=svgPoint(e.clientX,e.clientY),dx=p.x-CENTER.x,dy=p.y-CENTER.y;let raw=Math.atan2(dx,-dy)*180/Math.PI;raw=((raw%360)+360)%360;update(raw)}
function update(value){heading=normalize360(value);const signed=normalizeSigned(heading),relative=Math.abs(signed),zone=getZone(relative);if(relative>4&&relative<176)lastSide=signed>=0?1:-1;els.boatGroup.setAttribute("transform",`translate(500 420) rotate(${heading})`);updateSails(zone,lastSide);els.svgPointName.textContent=zone.label;els.factPoint.textContent=zone.label;els.factAngle.textContent=zone.angle;els.factTack.textContent=getTack(signed,relative);els.memoryText.textContent=zone.memory;els.trimText.textContent=zone.trim;document.querySelectorAll(".sector").forEach(s=>s.classList.toggle("active",s.dataset.zone===zone.key));els.buttons.forEach(b=>{const bz=getZone(Math.abs(normalizeSigned(Number(b.dataset.target))));b.classList.toggle("active",bz.key===zone.key);b.style.background=bz.key===zone.key?zone.color:""})}
function updateSails(zone,side){const s={noGo:{main:4,genoa:4,mainLen:114,genoaLen:118,opacity:.42},closeHauled:{main:13,genoa:10,mainLen:128,genoaLen:138,opacity:.78},closeReach:{main:22,genoa:22,mainLen:134,genoaLen:145,opacity:.78},beamReach:{main:46,genoa:42,mainLen:142,genoaLen:152,opacity:.80},broadReach:{main:68,genoa:62,mainLen:150,genoaLen:156,opacity:.82},deadRun:{main:84,genoa:-78,mainLen:148,genoaLen:150,opacity:.82}}[zone.key];let mainSide=side,genoaSide=side;if(zone.key==="deadRun"){mainSide=side;genoaSide=-side}els.mainSail.setAttribute("d",makeMainSail(mainSide*s.main,s.mainLen));els.genoaSail.setAttribute("d",makeGenoa(genoaSide*s.genoa,s.genoaLen));els.boomLine.setAttribute("d",makeBoom(mainSide*s.main,s.mainLen+6));els.mainSail.style.opacity=s.opacity;els.genoaSail.style.opacity=s.opacity}
function makeMainSail(angleDeg,length){const head={x:0,y:-82},tack={x:0,y:14},clew=projectFrom(tack.x,tack.y,angleDeg,length);return`M ${head.x} ${head.y} L ${tack.x} ${tack.y} L ${clew.x} ${clew.y} Z`}
function makeGenoa(angleDeg,length){const head={x:0,y:-158},tack={x:0,y:-54},clew=projectFrom(tack.x,tack.y,angleDeg,length);return`M ${head.x} ${head.y} L ${tack.x} ${tack.y} L ${clew.x} ${clew.y} Z`}
function makeBoom(angleDeg,length){const pivot={x:0,y:14},end=projectFrom(pivot.x,pivot.y,angleDeg,length);return`M ${pivot.x} ${pivot.y} L ${end.x} ${end.y}`}
function projectFrom(x,y,angleDeg,length){const rad=(angleDeg+90)*Math.PI/180;return{x:(x+Math.cos(rad)*length).toFixed(2),y:(y+Math.sin(rad)*length).toFixed(2)}}
function getZone(relative){return ZONES.find(z=>relative>=z.min&&relative<=z.max)||ZONES[ZONES.length-1]}
function getTack(signed,relative){if(relative<30)return"No tack / into wind";if(relative>176)return"Dead downwind";return signed>=0?"Port tack":"Starboard tack"}
function drawSectors(){ZONES.forEach(z=>{const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("class",`sector ${z.key==="noGo"?"no-go":""}`);p.setAttribute("data-zone",z.key);p.setAttribute("fill",z.color);p.setAttribute("d",sectorPath(z.min,z.max,RADIUS+42));els.sectorLayer.appendChild(p);if(z.min>0){const m=document.createElementNS("http://www.w3.org/2000/svg","path");m.setAttribute("class","sector");m.setAttribute("data-zone",z.key);m.setAttribute("fill",z.color);m.setAttribute("d",sectorPath(360-z.max,360-z.min,RADIUS+42));els.sectorLayer.appendChild(m)}})}
function sectorPath(min,max,radius){const p1=polar(min,radius),p2=polar(max,radius),largeArc=max-min>180?1:0;return`M 0 0 L ${p1.x} ${p1.y} A ${radius} ${radius} 0 ${largeArc} 1 ${p2.x} ${p2.y} Z`}
function polar(angleDeg,radius){const rad=(angleDeg-90)*Math.PI/180;return{x:(Math.cos(rad)*radius).toFixed(2),y:(Math.sin(rad)*radius).toFixed(2)}}
function drawTicks(){const ticks=document.querySelector("#ticks");for(let angle=0;angle<360;angle+=10){const major=angle%30===0,inner=major?228:240,outer=258,a=(angle-90)*Math.PI/180,x1=Math.cos(a)*inner,y1=Math.sin(a)*inner,x2=Math.cos(a)*outer,y2=Math.sin(a)*outer,line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttribute("x1",x1.toFixed(2));line.setAttribute("y1",y1.toFixed(2));line.setAttribute("x2",x2.toFixed(2));line.setAttribute("y2",y2.toFixed(2));line.setAttribute("stroke","rgba(10,37,64,.38)");line.setAttribute("stroke-width",major?"4":"2");line.setAttribute("stroke-linecap","round");ticks.appendChild(line)}}
function svgPoint(clientX,clientY){const pt=els.diagram.createSVGPoint();pt.x=clientX;pt.y=clientY;return pt.matrixTransform(els.diagram.getScreenCTM().inverse())}
function normalize360(value){return((value%360)+360)%360}function normalizeSigned(value){const n=normalize360(value);return n>180?n-360:n}function showToast(message){els.toast.textContent=message;els.toast.classList.add("visible");window.clearTimeout(showToast.timer);showToast.timer=window.setTimeout(()=>els.toast.classList.remove("visible"),3500)}
